export enum PositionType {
  LEFT_DEFENSEMAN = "LEFT_DEFENSEMAN",
  GOALTENDER = "GOALTENDER",
  RIGHT_DEFENSEMAN = "RIGHT_DEFENSEMAN",
  CENTER_DEFENSEMAN = "CENTER_DEFENSEMAN",
  LEFT_WINGER = "LEFT_WINGER",
  RIGHT_WINGER = "RIGHT_WINGER",
}
